"""init bot engine schema

Revision ID: 04eaccd50e75
Revises: 
Create Date: 2026-06-04 08:07:44.400599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04eaccd50e75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_trade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_trade_bot_id'), 'audit_log_trade', ['bot_id'], unique=False)
    op.create_index(op.f('ix_audit_log_trade_user_id'), 'audit_log_trade', ['user_id'], unique=False)
    op.create_table('bot_configs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('exchange', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_configs_user_id'), 'bot_configs', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('exchange', sa.String(length=40), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_bot_id'), 'orders', ['bot_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('exchange', sa.String(length=40), nullable=False),
    sa.Column('exchange_fill_id', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('fee', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('fee_currency', sa.String(length=20), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_bot_id'), 'fills', ['bot_id'], unique=False)
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    op.create_index(op.f('ix_fills_user_id'), 'fills', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fills_user_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_bot_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_bot_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_bot_configs_user_id'), table_name='bot_configs')
    op.drop_table('bot_configs')
    op.drop_index(op.f('ix_audit_log_trade_user_id'), table_name='audit_log_trade')
    op.drop_index(op.f('ix_audit_log_trade_bot_id'), table_name='audit_log_trade')
    op.drop_table('audit_log_trade')
    # ### end Alembic commands ###
